- name: Disable Nginx default version
  ansible.builtin.shell: dnf module disable nginx -y

- name: Enable Nginx 1.24 version
  ansible.builtin.shell: dnf module enable nginx:1.24 -y

- name: install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: installed

- name: Copy Nginx Config file
  ansible.builtin.copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Remove nginx default directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create Nginx Directory to copy required files
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Download and extract frontend content
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend-v3.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: Start nginx system-D service
  ansible.builtin.systemd_service:
    state: restarted
    name: nginx
    enabled: true