- name: Create an application user
  ansible.builtin.user:
    name: roboshop

- name: Remove Application directory
  ansible.builtin.file:
    path: /app
    state: absent
- name: Create Application directory
  ansible.builtin.file:
    path: /app
    state: directory